### PR TITLE
Downgrade to style-loader 2 to regain Webpack 4 compatibility

### PR DESCRIPTION
**Pull request by robintown**
This is a reintroduction of https://github.com/vector-im/element-web/pull/23894 since https://github.com/vector-im/element-web/pull/24027 regressed it. style-loader 3 isn't compatible with Webpack 4, and causes build errors:

```
2023-01-03 20:29:40.725 [element-js] ERROR in ../matrix-react-sdk/res/themes/light/css/light.pcss
2023-01-03 20:29:40.725 [element-js] Module build failed (from ./node_modules/style-loader/dist/cjs.js):
2023-01-03 20:29:40.725 [element-js] TypeError: this.getOptions is not a function
2023-01-03 20:29:40.725 [element-js]     at Object.loader (/home/robin/code/element-web/element-web/node_modules/style-loader/dist/index.js:19:24)
```

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Review by turt2live — APPROVED** [review]

**Comment by turt2live** [comment]
regressed by https://github.com/vector-im/element-web/pull/24027
