### ISSUE TITLE
Can't start DM from right panel

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#24722]
### Steps to reproduce

1. User1 send the MXID of user2 in a message
2. Click on MXID of user2 to open them in the right panel
3. Click on "Message" to start your first DM with user2

#### What did you expect?
Go to the new DM and send my first message

#### What happened instead?
Infinispinner when hovering over "Message" in the right panel, DM doesn't start

![Screenshot from 2023-03-02 11-23-40](https://user-images.githubusercontent.com/51663/222425005-7cd848bc-ef09-445a-a700-5ce60cbeec8b.png)

Searching for the user in the user directory finds and starts a DM with them

### Browser information

Chromium 110.0.5481.177 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: 3903e86d9cfb-react-de6a1a661cc9-js-41782c4593b4 Olm version: 3.2.12

### Homeserver

matrix.org trying to start DM with half-shot.uk

### Will you send logs?

No

**Comment by t3chguy** [comment]
@weeman1337 could this be a regression due to https://github.com/matrix-org/matrix-react-sdk/pull/10256

**Comment by weeman1337** [comment]
Unfortunately I cannot reproduce (users from different homeservers):

![dm](https://user-images.githubusercontent.com/6216686/222427783-06a789d1-98e6-45e7-80f9-2c9f2993f603.gif)

@kittykat can you send logs?

**Comment by weeman1337** [comment]
Found in a live debug session with kat:

```
Uncaught (in promise) TypeError: user.getMxcAvatarUrl is not a function
    at openDMForUser (element-web-app.js:18359:22)
    at onClick (element-web-app.js:18545:13)
    at Object.Rb (vendors~init.js:71910:317)
    at Xb (vendors~init.js:71910:471)
    at Yb (vendors~init.js:71911:35)
    at Ze (vendors~init.js:71958:68)
    at se (vendors~init.js:71959:380)
    at vendors~init.js:71971:65
    at Jb (vendors~init.js:72150:189)
    at Nb (vendors~init.js:71908:57)
```

This information was not in the logs :disappointed:

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/222447261-aed68983-52db-4ba2-b2cd-dfff288b85dd.png)

The issue is here, the member can be `RoomMember | User` 
![image](https://user-images.githubusercontent.com/2403652/222447337-4b899eae-4a1b-43db-8764-a2548563ad38.png)

So the components downstream are making the wrong assumptions
